#!/bin/bash
set -e

show_help() {
    cat << HELP_TEXT
$0 [options]
Generates a svg file with the influence areas of the given dataset.
Input is read on stdin, output is written in stdout.

Options:
--width <N>
--height <N>
    Choose the dimensions of the image.
    Default value: 500 (for both).

--expand <F>
    Percentage of the dataset extension that should be used as border.
    Default value: 0.05.

--help
    Display this help and exit.

Classifier options:
These options are passed directly to the classifier.
Run .classify --help for more information.
--manhattan
--hamming
--euclidean
--neighbors <N>
--normalize-tolerance <F>
HELP_TEXT
}

width=500
height=500
expand=0.05
distance_type=""
neighbors=""
normalization=""

while (($# != 0)); do
    case "$1" in
    (--width)
        width="$2"
        shift
        ;;
    (--height)
        height="$2"
        shift
        ;;
    (--help)
        show_help "$@"
        exit 0
        ;;
    (--expand)
        expand="$2"
        shift
        ;;
    (--manhattan | --hamming | --euclidean)
        distance_type="$1"
        ;;
    (--neighbors)
        neighbors="--neighbors $2"
        shift
        ;;
    (--normalize-tolerance)
        normalization="--normalize-tolerance $2"
        shift
        ;;
    (*)
        echo Unrecognized option "$1" >&2
        exit 1
        ;;
    esac
    shift
done

dataset=$(mktemp --tmpdir)
grid=$(mktemp --tmpdir)
answers=$(mktemp --tmpdir)
output=$(mktemp --tmpdir)

cat - > "$dataset"

datatools/generate_entry_grid --dimensions "$width","$height" \
    --expand "$expand" < "$dataset" > "$grid"

./classify --dataset "$dataset" < "$grid" > "$answers" \
    $distance_type $neighbors $normalization

cat "$dataset" <(paste -d , "$grid" "$answers") > "$output"

datatools/generate_svg --width "$width" --height "$height" --radius 1 < "$output"

rm -f "$dataset" "$grid" "$answers" "$output"
