#!/bin/bash
set -e

show_help() {
    cat << HELP_TEXT
$0 [options]
Generates a svg file with the influence areas of the given dataset.
Input is read on stdin, output is written in stdout.

Options:
--width <N>
--height <N>
    Choose the dimensions of the image.
    Default value: 500 (for both).

--density <N>
    A single pixel categorization can be used to fill more than
    a single pixel in the output. This value controls the
    "radius of influence" of each pixel.
    The smaller is this value, the greater is the quality
    of the output, and the greater is the run time.
    Default: 3.
    Note there is no point in chosing a value smaller than 1.

--expand <F>
    Percentage of the dataset extension that should be used as border.
    Default value: 0.05.

--help
    Display this help and exit.

Classifier options:
These options are passed directly to the classifier.
Run .classify --help for more information.
--manhattan
--hamming
--euclidean
--neighbors <N>
--normalize-tolerance <F>
HELP_TEXT
}

width=500
height=500
density=3
expand=0.05
distance_type=""
neighbors=""
normalization=""

while (($# != 0)); do
    case "$1" in
    (--width)
        witdth="$2"
        shift
        ;;
    (--height)
        height="$2"
        shift
        ;;
    (--density)
        density="$2"
        shift
        ;;
    (--help)
        show_help "$@"
        exit 0
        ;;
    (--expand)
        expand="$2"
        shift
        ;;
    (--manhattan | --hamming | --euclidean)
        distance_type="$1"
        ;;
    (--neighbors)
        neighbors="--neighbors $2"
        shift
        ;;
    (--normalize-tolerance)
        normalization="--normalize-tolerance $2"
        shift
        ;;
    (*)
        echo Unrecognized option "$1" >&2
        exit 1
        ;;
    esac
    shift
done

grid_x=$(bc <<< "$width / $density")
grid_y=$(bc <<< "$height / $density")
dataset=$(mktemp --tmpdir)
grid=$(mktemp --tmpdir)
answers=$(mktemp --tmpdir)
output=$(mktemp --tmpdir)

cat - > "$dataset"

datatools/generate_entry_grid --dimensions "$grid_x","$grid_y" \
    --expand "$expand" < "$dataset" > "$grid"

./classify --dataset spiral.data < "$grid" > "$answers"

cat "$dataset" <(paste -d , "$grid" "$answers") > "$output"

datatools/generate_svg < "$output"

rm -f "$dataset" "$grid" "$answers" "$output"
